name: CI/CD Workflow

on:
  push:
    branches:
      - "feature/**"

jobs:
  Continues-Integrations-Jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create config.properties file
        run: |
          echo "APIKEY_DEV=${{ secrets.APIKEY_DEV }}" > $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_DEV_PREPAID=${{ secrets.BASE_URL_DEV_PREPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_PROD_PREPAID=${{ secrets.BASE_URL_PROD_PREPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APIKEY_PROD=${{ secrets.APIKEY_PROD }}" >> $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_DEV_POSTPAID=${{ secrets.BASE_URL_DEV_POSTPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_PROD_POSTPAID=${{ secrets.BASE_URL_PROD_POSTPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_ADS_DEV=${{ secrets.APP_ADS_DEV }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_BANNER_DEV=${{ secrets.APP_BANNER_DEV }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_ADS_PROD=${{ secrets.APP_ADS_PROD }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_BANNER_PROD=${{ secrets.APP_BANNER_PROD }}" >> $GITHUB_WORKSPACE/config.properties
          echo "GOOGLE_SERVICES_JSON_2=${{ secrets.GOOGLE_SERVICES_JSON_2 }}" >> $GITHUB_WORKSPACE/app/google-services.json
          echo "GOOGLE_SERVICES_JSON_2=${{ secrets.GOOGLE_SERVICES_JSON_2 }}" >> $GITHUB_WORKSPACE/google-services.json

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 20

      - name: Grand execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Clean Test
        run: ./gradlew clean test

  Continues-Delivery-Jobs:
    runs-on: ubuntu-latest
    needs: Continues-Integrations-Jobs
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 20

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Grand execute permissions to gradlew
        run: chmod +x gradlew

      - name: Create config.properties file
        run: |
          echo "APIKEY_DEV=${{ secrets.APIKEY_DEV }}" > $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_DEV_PREPAID=${{ secrets.BASE_URL_DEV_PREPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_PROD_PREPAID=${{ secrets.BASE_URL_PROD_PREPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APIKEY_PROD=${{ secrets.APIKEY_PROD }}" >> $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_DEV_POSTPAID=${{ secrets.BASE_URL_DEV_POSTPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "BASE_URL_PROD_POSTPAID=${{ secrets.BASE_URL_PROD_POSTPAID }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_ADS_DEV=${{ secrets.APP_ADS_DEV }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_BANNER_DEV=${{ secrets.APP_BANNER_DEV }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_ADS_PROD=${{ secrets.APP_ADS_PROD }}" >> $GITHUB_WORKSPACE/config.properties
          echo "APP_BANNER_PROD=${{ secrets.APP_BANNER_PROD }}" >> $GITHUB_WORKSPACE/config.properties


      - name: Build QA Flavour APK
        run: ./gradlew assembleDebug

      - name: Upload QA Flavour APK to Firebase App Tester
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.QA_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: qa
          releaseNotes: ${{ github.event.head_commit.message }}
          file: app/build/outputs/apk/debug/app-debug.apk